server:
  port: 8090

spring:
  application:
    name: edu-config-boot
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yemjzzz/lagou-edu-repo.git
          username: 15868861259
          password: ymjqq1042965192@
          default-label: master